# C tests targeting wasm32-wasip1 via wasi-sdk.
_TESTS = [
    "clock_getres-monotonic",
    "clock_getres-realtime",
    "clock_gettime-monotonic",
    "clock_gettime-realtime",
    "fdopendir-with-access",
    "fopen-with-access",
    "fopen-with-no-access",
    "lseek",
    "pread-with-access",
    "pwrite-with-access",
    "pwrite-with-append",
    "sock_shutdown-invalid_fd",
    "sock_shutdown-not_sock",
    "stat-dev-ino",
]

[
    cxx_binary(
        name = t,
        srcs = ["src/{}.c".format(t)],
        _cxx_toolchain = "toolchains//:cxx_wasi_p1",
        visibility = ["//tests/..."],
    )
    for t in _TESTS
]
