load("@wasmono//toolchains/wasm:assemblyscript.bzl", "assemblyscript_binary")

# AssemblyScript wasip1 tests: compile only.
# Test execution is handled by conformance tests in //tests:BUCK.

_TESTS = [
    "args_get-multiple-arguments",
    "args_sizes_get-multiple-arguments",
    "args_sizes_get-no-arguments",
    "environ_get-multiple-variables",
    "environ_sizes_get-multiple-variables",
    "environ_sizes_get-no-variables",
    "fd_write-to-invalid-fd",
    "fd_write-to-stdout",
    "proc_exit-failure",
    "proc_exit-success",
    "random_get-non-zero-length",
    "random_get-zero-length",
]

[
    assemblyscript_binary(
        name = t,
        src = "src/{}.ts".format(t),
        visibility = ["//tests/..."],
    )
    for t in _TESTS
]
