load("@wasmono//toolchains/wasm:component.bzl", "wasm_component")

# Rust wasip3 tests: compile + create components.
# Test execution is handled by conformance tests in //tests:BUCK.

_TESTS = [
    "cli-env",
    "cli-exit",
    "cli-stdio",
    "cli-stdio-roundtrip",
    "cli-terminal",
    "filesystem-advise",
    "filesystem-dotdot",
    "filesystem-flags-and-type",
    "filesystem-hard-links",
    "filesystem-io",
    "filesystem-is-same-object",
    "filesystem-metadata-hash",
    "filesystem-mkdir-rmdir",
    "filesystem-open-errors",
    "filesystem-read-directory",
    "filesystem-rename",
    "filesystem-set-size",
    "filesystem-stat",
    "filesystem-unlink-errors",
    "http-fields",
    "http-request",
    "http-response",
    "http-service",
    "monotonic-clock",
    "multi-clock-wait",
    "random",
    "run-with-err",
    "sockets-echo",
    "sockets-tcp-bind",
    "sockets-tcp-connect",
    "sockets-tcp-listen",
    "sockets-tcp-properties",
    "sockets-tcp-receive",
    "sockets-tcp-send",
    "sockets-udp-bind",
    "sockets-udp-connect",
    "sockets-udp-properties",
    "sockets-udp-receive",
    "sockets-udp-send",
    "wall-clock",
]

_WIT_SRCS = glob(["wit/**/*.wit"])

# Shared test library with wit_bindgen::generate! modules
rust_library(
    name = "test_wasm32_wasip3",
    crate = "test_wasm32_wasip3",
    srcs = [
        "src/lib.rs",
        "src/cli.rs",
        "src/clocks.rs",
        "src/http.rs",
        "src/random.rs",
        "src/sockets.rs",
    ] + _WIT_SRCS,
    edition = "2024",
    default_target_platform = "//platforms:wasm32_wasi",
    deps = [
        "//third-party:wit-bindgen",
    ],
    env = {"CARGO_MANIFEST_DIR": "."},
    _cxx_toolchain = "toolchains//:rust_linker",
)

# Individual test binaries + components
[
    (
        rust_binary(
            name = t,
            crate = t.replace("-", "_"),
            crate_root = "src/bin/{}.rs".format(t),
            srcs = ["src/bin/{}.rs".format(t)] + _WIT_SRCS,
            edition = "2024",
            default_target_platform = "//platforms:wasm32_wasi",
            deps = [
                ":test_wasm32_wasip3",
                "//third-party:wit-bindgen",
                "//third-party:futures",
            ],
            env = {"CARGO_MANIFEST_DIR": "."},
            _cxx_toolchain = "toolchains//:rust_linker",
        ),
        wasm_component(
            name = t + "_component",
            module = ":{}".format(t),
            adapter = "command",
            visibility = ["//tests/..."],
        ),
    )
    for t in _TESTS
]
