export_file(
    name = "run_wasi_test.py",
    src = "run_wasi_test.py",
    visibility = ["PUBLIC"],
)

export_file(
    name = "generate_manifest.py",
    src = "generate_manifest.py",
    visibility = ["PUBLIC"],
)

export_file(
    name = "package_dist.py",
    src = "package_dist.py",
    visibility = ["PUBLIC"],
)
