python_library(
    name = "run_wasi_test",
    srcs = ["run_wasi_test.py"],
    base_module = "",
    deps = [
        "//test-runner:wasi_test_runner",
        "//adapters:adapters",
    ],
    visibility = ["PUBLIC"],
)

export_file(
    name = "generate_manifest.py",
    src = "generate_manifest.py",
    visibility = ["PUBLIC"],
)

export_file(
    name = "package_dist.py",
    src = "package_dist.py",
    visibility = ["PUBLIC"],
)
